version: '3'
services:
  playground:
    container_name: playground
    build: .
    volumes:
    - ./app:/app
    - playground-logs:/var/log
    links:
    - edgedb
    depends_on:
    - edgedb
  edgedb:
    container_name: edgedb-pg
    image: edgedb/edgedb:1-alpha2
    ports:
    - "5656:5656" # EdgeQL over binary protocol
    - "8889:8889" # EdgeQL over HTTP
    - "8888:8888" # GraphQL over HTTP
    volumes:
    - edgedb-db:/var/lib/edgedb/data
volumes:
  edgedb-db: {}
  playground-logs: {}